name: Build

on: [push, pull_request]

permissions:
    contents: read

jobs:
    node:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [22.x, 24.x]
        steps:
            - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install dependencies
              run: npm ci
            - name: Jest
              uses: Forsakringskassan/jest-config@e2a13e332722a2b86d30eff01fa5561d1e2bf3c9 # v30.4.0
            - name: Build
              run: npm run --if-present build

    lint:
        name: Lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
            - name: Use Node.js 22.x
              uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
              with:
                  node-version: 22.x
            - name: Install dependencies
              run: npm ci
            - name: Prettier
              uses: Forsakringskassan/prettier-config@9f68ea9b6d1a3329ff59178e5cba8e3e6eafc407 # v3.7.6
            - name: ESLint
              if: success() || failure()
              uses: Forsakringskassan/eslint-config@8742bcf2942a0d25f09593c949076ec9aaedc95a # v15.2.0

    npm-pkg-lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
            - name: Use Node.js
              uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
            - name: Install Dependencies
              run: npm ci
            - name: npm-pkg-lint
              uses: ext/npm-pkg-lint@b70ccc4ad5e23e66267070907ef88174419b99dc # v5.1.10

    cypress:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                cypress-version: [15.x]
        steps:
            - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
            - name: Use Node.js 22
              uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
              with:
                  node-version: 22
            - name: Install dependencies
              run: npm ci
            - name: Build
              run: npm run --if-present build
            - name: Install Cypress ${{ matrix.cypress-version }}
              run: npm install cypress@${{ matrix.cypress-version }}
            - name: Cypress
              run: npm exec cypress run
