name: Build

on: [push, pull_request]

jobs:
    node:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [20.x, 22.x]
        steps:
            - uses: actions/checkout@v5
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v5
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install dependencies
              run: npm ci
            - name: Jest
              run: npm exec jest -- --ci
            - name: Build
              run: npm run --if-present build

    lint:
        name: Lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - name: Use Node.js 20.x
              uses: actions/setup-node@v5
              with:
                  node-version: 20.x
            - name: Install dependencies
              run: npm ci
            - name: Prettier
              run: npm run prettier:check
            - name: ESLint
              if: success() || failure()
              run: npm run eslint || false

    npm-pkg-lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - name: Use Node.js
              uses: actions/setup-node@v5
            - name: Install Dependencies
              run: npm ci
            - name: npm-pkg-lint
              uses: ext/npm-pkg-lint@master

    cypress:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                cypress-version: [12.x, 13.x, 14.x, 15.x]
        steps:
            - uses: actions/checkout@v5
            - name: Use Node.js 20
              uses: actions/setup-node@v5
              with:
                  node-version: 20
            - name: Install dependencies
              run: npm ci
            - name: Build
              run: npm run --if-present build
            - name: Install Cypress ${{ matrix.cypress-version }}
              run: npm install cypress@${{ matrix.cypress-version }}
            - name: Cypress
              run: npm exec cypress run
